# Generated by Django 4.0.1 on 2022-01-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artistss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('i_d', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('img1', models.ImageField(upload_to='pics/')),
                ('img2', models.ImageField(upload_to='pics/')),
                ('img3', models.ImageField(upload_to='pics/')),
                ('availaible', models.BooleanField(default=False)),
            ],
        ),
    ]
